title: Aniqa Sattar # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Web Developer></b> 
  <br><br>
  Self-motivated, team-work oriented and professional web developer, experience in the development of responsive web designing using HTML, CSS, JavaScript, Bootstrap, and jQuery, familiarity with Angular, 
  willing to learn new traits and can work independently and as a part of a team.  
  <br><br>
#<a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here